### ISSUE TITLE
Issue with the Background Colour on the Header

### ISSUE THREAD

**Issue by bensullivan8** [bensullivan8/kraken-good-accessibility#1]
From our Slack conversation...
"So for the Kraken assignment, the only thing that I’m having trouble with getting to pass is the background colour of the header, but I have it set at #1E7C74 which is the right colour code I believe. Otherwise, no other issues from Markbot."
I also do believe I gave the header the SVG patterned background. But obviously, I could have done it wrong.

Thanks,
@hellachella

**Comment by hellachella** [comment]
What is markbot saying? This looks like it's working for me. Like it is identical and your code for it is correct. 


<img width="985" alt="Screen Shot 2020-10-09 at 5 07 05 PM" src="https://user-images.githubusercontent.com/10465921/95631631-06a4ed00-0a52-11eb-9285-e28289203f38.png">

**Comment by bensullivan8** [comment]
Odd... This is what Markbot is still showing me @hellachella...
<img width="1064" alt="Screen Shot 2020-10-10 at 12 51 31 AM" src="https://user-images.githubusercontent.com/55108838/95646089-ec3f3380-0a92-11eb-9d19-2f23f27058d7.png">

**Comment by hellachella** [comment]
Manually grading.
